### ISSUE TITLE
where to download the latest version APP (eComm And comment)?

### ISSUE THREAD

**Issue by YoChen** [MrCMS/MrCMS#1]
hi?
when to download the two app?Waiting for a long time.

**Comment by Will-Bill** [comment]
Keep an eye out here: https://github.com/MrCMS

Commenting and Page-Stats apps have been shared.

**Comment by YoChen** [comment]
Thanks very much.
and how to set Comment?
I have add the comment app,and admin/Comments/Settings have added Article had comments.but infront no view.

**Comment by YoChen** [comment]
ok,I know.
First I sholud add a layout arer "Comments" to Default Layout manage.eg Base Layout.
Sencond. config the comments for document type or ACL.
Thanks. and look faword the Ecommerce APP.

**Comment by Will-Bill** [comment]
Yes you need to add a layout area called comments. And then add the widget current page widgets I think its called. In settings you should set which page types you want it to work on.


Sent by Outlook<http://taps.io/outlookmobile> for Android



On Sun, May 10, 2015 at 1:05 AM -0700, "YoChen" <notifications@github.com<mailto:notifications@github.com>> wrote:


ok,I know.
First I sholud add a layout arer "Comments" to Default Layout manage.eg Base Layout.
Sencond. config the comments for document type or ACL.
Thanks. and look faword the Ecommerce APP.

-

**Comment by gmstr** [comment]
Just to be clear, the layout area name is irrelevant, it's just about adding the widget into the page wherever you want it to be.

**Comment by YoChen** [comment]
Thanks All helps.
