### ISSUE TITLE
Need this function.

### ISSUE THREAD

**Issue by YoChen** [MrCMS/MrCMS#10]
Can provide such a function？
make choose pages generate static pages.

Thanks.

**Comment by Will-Bill** [comment]
Sorry not sure what you mean, please can you expand?

**Comment by YoChen** [comment]
can make all page to html

**Comment by Will-Bill** [comment]
For what reason do you want to do this?

**Comment by YoChen** [comment]
yes,I want to  publish a site to another servers.
frontweb can run without no web admin.
so more sites can published to different servers.

**Comment by Will-Bill** [comment]
Unfortunately this is not something we intend on supporting.

Have you thought about using multi-site functionality?
