### ISSUE TITLE
DNC LatestXArticles

### ISSUE THREAD

**Issue by kschost100** [MrCMS/MrCMS#100]
So i added some articles and then tried to use the widget LatextXArticles and this is what happens, 

`fail: MrCMS.Logging.MrCMSLoggingMiddleware[0]
      The view 'Components/Widget/LatestXArticles' was not found. The following locations were searched:
      /Themes/Red/Apps/Core/Views/TextPage/Components/Widget/LatestXArticles.en-US.cshtml
      /Themes/Red/Apps/Core/Views/TextPage/Components/Widget/LatestXArticles.en.cshtml
      /Themes/Red/Apps/Core/Views/TextPage/Components/Widget/LatestXArticles.cshtml
      /Apps/Core/Views/TextPage/Components/Widget/LatestXArticles.en-US.cshtml
      /Apps/Core/Views/TextPage/Components/Widget/LatestXArticles.en.cshtml
      /Apps/Core/Views/TextPage/Components/Widget/LatestXArticles.cshtml
      /Themes/Red/Views/TextPage/Components/Widget/LatestXArticles.en-US.cshtml
      /Themes/Red/Views/TextPage/Components/Widget/LatestXArticles.en.cshtml
      /Themes/Red/Views/TextPage/Components/Widget/LatestXArticles.cshtml
      /Views/TextPage/Components/Widget/LatestXArticles.en-US.cshtml
      /Views/TextPage/Components/Widget/LatestXArticles.en.cshtml
      /Views/TextPage/Components/Widget/LatestXArticles.cshtml
      /Themes/Red/Apps/Core/Views/Shared/Components/Widget/LatestXArticles.en-US.cshtml
      /Themes/Red/Apps/Core/Views/Shared/Components/Widget/LatestXArticles.en.cshtml
      /Themes/Red/Apps/Core/Views/Shared/Components/Widget/LatestXArticles.cshtml
      /Apps/Core/Views/Shared/Components/Widget/LatestXArticles.en-US.cshtml
      /Apps/Core/Views/Shared/Components/Widget/LatestXArticles.en.cshtml
      /Apps/Core/Views/Shared/Components/Widget/LatestXArticles.cshtml
      /Themes/Red/Views/Shared/Components/Widget/LatestXArticles.en-US.cshtml
      /Themes/Red/Views/Shared/Components/Widget/LatestXArticles.en.cshtml
      /Themes/Red/Views/Shared/Components/Widget/LatestXArticles.cshtml
      /Views/Shared/Components/Widget/LatestXArticles.en-US.cshtml
      /Views/Shared/Components/Widget/LatestXArticles.en.cshtml
      /Views/Shared/Components/Widget/LatestXArticles.cshtml
      /Themes/Red/Apps/Core/Pages/Shared/Components/Widget/LatestXArticles.en-US.cshtml
      /Themes/Red/Apps/Core/Pages/Shared/Components/Widget/LatestXArticles.en.cshtml
      /Themes/Red/Apps/Core/Pages/Shared/Components/Widget/LatestXArticles.cshtml
      /Apps/Core/Pages/Shared/Components/Widget/LatestXArticles.en-US.cshtml
      /Apps/Core/Pages/Shared/Components/Widget/LatestXArticles.en.cshtml
      /Apps/Core/Pages/Shared/Components/Widget/LatestXArticles.cshtml
      /Themes/Red/Pages/Shared/Components/Widget/LatestXArticles.en-US.cshtml
      /Themes/Red/Pages/Shared/Components/Widget/LatestXArticles.en.cshtml
      /Themes/Red/Pages/Shared/Components/Widget/LatestXArticles.cshtml
      /Pages/Shared/Components/Widget/LatestXArticles.en-US.cshtml
      /Pages/Shared/Components/Widget/LatestXArticles.en.cshtml
      /Pages/Shared/Components/Widget/LatestXArticles.cshtml
System.InvalidOperationException: The view 'Components/Widget/LatestXArticles' was not found. The following locations were searched:`

Seems it is not looking for the Articles Views.
Any Ideas?

**Comment by Will-Bill** [comment]
Hey, 

This is just the views being in the wrong place. See this commit which fixes: https://github.com/MrCMS/MrCMS/commit/04e8982157ca8a9bc070fc88cc39806d8f57fe95

Should be in Views/Shared/Components/Widget not Views/Widgets.

Some other fixes coming in just as a heads up - worth patching the latest dotnetcore branch changes as they come in.

Cheers

**Comment by kschost100** [comment]
Awesome, Thank you
