### ISSUE TITLE
MrCMS crashes when multiple request is made immediately after startup (DNC 3.1)

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#110]
I noticed a bug but couldn't place my hand on the cause until now. The application will suddenly just stop browsing especially after some long idleness when hosted, Most webserver have a maximum idle timeout in which the thread or worker will shut down. I was able to overcome this by using CRON for polling the site for a duration less than the idle timeout of the server.

However, the situation still persisted online and sometimes locally, on further investigation. I now realized that it is the wake up activity after idleness that has issues. I have a separate React App calling some API on the application, anytime the app sends a multiple fetch request to the MrCMS application and the kestrel server has to start-up because it was idle, then the application will not work but if you send a single fetch request when the application just started up, there won't be problem, everything works fine

So I noticed that whenever the MrCMS starts up, you must never send a multiple fetch request as the first request to the server, it will somehow crash the server but if you send a single request, no problem at all. 

I was able to reproduce the error using healthcheck feature of asp.net core. I added AspNetCore.HealthChecks.Uris packaged to MrCMS.web and created publisher class to see the result of calling the Urls

```
public class ReadinessPublisher : IHealthCheckPublisher
    {
        private readonly ILogger _logger;

        public ReadinessPublisher(ILogger<ReadinessPublisher> logger)
        {
            _logger = logger;
        }

        public Task PublishAsync(HealthReport report, CancellationToken cancellationToken)
        {
            if (report.Status == HealthStatus.Healthy)
            {
                _logger.LogInformation("{Timestamp} Readiness Probe Status: {Result}", 
                    DateTime.UtcNow, report.Status);
            }
            else
            {
               
               

                _logger.LogError("{Timestamp} Readiness Probe Status: {Result}", 
                    DateTime.UtcNow, report.Status);
               

                foreach (var entry in report.Entries)
                {
                    var exception = entry.Value.Exception;
                    var errorMessage = entry.Value.Exception.Message ?? "";
                   // var errorSource = report.Entries.First().Value.Exception.Source ?? "";
                   // var exceptionInnerException = report.Entries.First().Value.Exception.InnerException;
                   // var error = exceptionInnerException == null ? "" : exceptionInnerException.Message;
                    _logger.LogError(exception, errorMessage);
                }
            }

            cancellationToken.ThrowIfCancellationRequested();

            return Task.CompletedTask;
        }
    }
```
And added the following to the ConfigureServices method in startup.cs

```
services.Configure<HealthCheckPublisherOptions>(options =>
            {
                options.Delay = TimeSpan.FromSeconds(5);
                options.Period = TimeSpan.FromMinutes(60);
            });

            if (IsInstalled())
            {
                services.AddHealthChecks()
                    .AddUrlGroup(new Uri("https://localhost:44301/register"), "API 1")
                    .AddUrlGroup(new Uri("https://localhost:44301/page-2"), "API 2");;
            }
          
            
            services.AddSingleton<IHealthCheckPublisher, ReadinessPublisher>();
```
If you comment out one Url Check and leave only one Url Check, the application will work but if you leave the 2 Url Checks, the application will not work. I later tested this process on a normal asp.net project and it worked perfectly

I though it was probably my apps, I had to rebuild MrCMS without any of my apps and I even download the latest version or commit and the problem still persist.

The interesting part is that the problem occurs only on Kestrel but if I use IIS express, it works fine but most hosting uses Kestrel, thus the issue will always occur on hosting servers

**Comment by carlospence** [comment]
The problem is with MrCMSDatabaseLoggerProvider.cs

I re-wrote the CreateLogger method
```
public ILogger CreateLogger(string categoryName)
        {
            return loggers.GetOrAdd(categoryName,
                (category) => {
                    return new MrCMSDatabaseLogger(_contextAccessor);
                });
            // var httpContext = _serviceProvider.GetRequiredService<IHttpContextAccessor>().HttpContext;
            // if (httpContext == null)
            // {
            //     return NullLogger.Instance; 
            // }
            //   
            // return httpContext.RequestServices.GetRequiredService<MrCMSDatabaseLogger>();
        }

```

**Comment by gmstr** [comment]
I had spotted similar behaviour when working on something recently, but hadn't had chance to track it down, this looks like a good spot, thanks. 

Just playing with it here based on that snippet, and it looks like it's reliable here with this version of MrCMSDatabaseLoggerProvider.cs:

```
using System;
using System.Collections.Concurrent;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace MrCMS.Logging
{
    public class MrCMSDatabaseLoggerProvider : ILoggerProvider
    {
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IServiceProvider _serviceProvider;

        private readonly ConcurrentDictionary<string, MrCMSDatabaseLogger> Loggers =
            new ConcurrentDictionary<string, MrCMSDatabaseLogger>();

        public MrCMSDatabaseLoggerProvider(IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
        }

        public void Dispose()
        {
        }

        public ILogger CreateLogger(string categoryName)
        {
            return Loggers.GetOrAdd(categoryName,
                s => new MrCMSDatabaseLogger(_contextAccessor));
        }
    }
}
```

If that works at that end, I'll get that rolled back into the repo when I get a moment.

**Comment by carlospence** [comment]
Sure, it works well since I introduced this snippet. I believe you can roll it into the repo.
