### ISSUE TITLE
Registering new Area

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#16]
Goodday,

I have tried creating and registering a new Area on Mr CMS but to no avail. 

I always get this error: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

This is my code below

    public class StudentAreaRegistration : AreaRegistration 
      {
       

      public override string AreaName 
        {
            get 
            {
                return "Student";
            }
        }

        public override void RegisterArea(AreaRegistrationContext context) 
        {
           
            context.MapRoute(
                "Student_default",
                "Student/{controller}/{action}/{id}",
                new {controller = "Home", action = "Index", id = UrlParameter.Optional }
            );
        }
    }
I have a HomeController and an Index.cshtml inside a Home folder in the views folder. I don't know what I am missing.

**Comment by Will-Bill** [comment]
Hello. Please register your routes within the App you are creating. See MrCMS.Web/Apps/Core/CoreApp.cs RegisterApp where you can map routes.

**Comment by carlospence** [comment]
Hello Will,

I have register my routes in my app but its still not working.

   context.MapAreaRoute("CollegeCBT student controllers", "Students",
                "Student/Apps/CollegeCBT/{controller}/{action}/{id}",
                new { controller = "Home", action = "Index", id = UrlParameter.Optional },
                  new[] { typeof(StudentPageController).Namespace });

 context.MapAreaRoute("CollegeCBT student controllers2", "Students",
               "Students/{controller}/{action}/{id}",
               new { controller = "Home", action = "Index", id = UrlParameter.Optional },
                 new[] { typeof(StudentPageController).Namespace });

I later remove the namespace parameter but its still not working. Do you have a sample I can follow.

**Comment by Will-Bill** [comment]
AdminAreaRegistration.cs is an example of registering an area. The are more examples of route registration in EcommerceApp.

**Comment by carlospence** [comment]
I have used your EcomerceApp to create a new Area called Students and I have created
