### ISSUE TITLE
Mr CMS Caching

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#17]
While working and testing my app, I sometimes need fresh installation of Mr CMS, so I do delete the content of App_Data and sometimes the database but the installation setup is not activated immediately instead different errors do pop up depending on various factors. I noticed that the settings information is cached somewhere and I have to wait for the cache to expire before the fresh installation is activated. Where is the caching stored or how can I burst the cache manually

**Comment by carlospence** [comment]
If I change the webserver port, it starts up immediately

**Comment by Will-Bill** [comment]
Settings are stored in memory for fast access. If you want to start fresh just kill IIS Express or change the port as you say.

If the project is running there is a clear cache button under the system menu.
