### ISSUE TITLE
Page Templates

### ISSUE THREAD

**Issue by jmalatia** [MrCMS/MrCMS#21]
Is there a place that "Page Templates" is explained?  We can't seem to get them to work... maybe we are not understanding how they are supposed to be used?  But we created two and tried to assign them to some pages and after saving those pages we get a 500 error page returned.

Also, how do you delete "Page Templates"?  There doesn't seem to be a DELETE button on the Page Templates page '/Admin/PageTemplate'

**Comment by Will-Bill** [comment]
Hi There, 

Sorry documentation is still something we are sorely lacking.

Page templates allow you to reuse a page type / model but allow you to use a different view and/or layout and/or URL generator.

Say for example you wanted a new page called 'Home' which you were happy just using the TextPage page type you could create a new Page Template called 'Home'. When adding the Page template in the Page View Name field write the name of the view. For example HomePage - do not include the file extension. Make sure this view exists in your theme / app views folder.

The page type drop down would be set to TextPage and the layout/generator can just be defaulted. Single use means the new page template can only be used one time.

To use this new page you can do one of two things:

1) If the page already exists that you want to use this with, navigate to the edit screen for the page type and set it up the layout tab

2) If the page hasn't been added yet right click and add a page as you would normally, you will see "HomePage" is now an option to be added to the site.

Shout if you need more clarification
