### ISSUE TITLE
Using Database for Settings

### ISSUE THREAD

**Issue by rbailo** [MrCMS/MrCMS#22]
Hello, I was wondering with the new version am i able to use the database to store settings. and Stats. I am more comfortable with Sql than json.

**Comment by Will-Bill** [comment]
In the next version of Mr CMS settings and Message templates are moved back to the database for more portability and compatibility with Azure.

You shouldn't really need to manage the settings on disk, all settings are editable through the admin system (Admin -> System -> Site Settings)

**Comment by rbailo** [comment]
Thank you, I dont intend to edit settings from outside the application, just not a fan of storing information in 2 locations, Understandable the database info being stored local, and not having anything against the way you did your setup, its actually a very nice application. I did manage to trace everything to place it in the database. Any plans for compact server in the future. Also do you need any help with the project, I will have free time starting next month.

**Comment by Will-Bill** [comment]
When we tried compact server it didn't have the require functionality that we required to run Mr CMS. SQLite has far more functionality out the box. We may revisit this in the future with .NET Core and EF Core etc.
