### ISSUE TITLE
One article to many article list

### ISSUE THREAD

**Issue by wwl2013** [MrCMS/MrCMS#23]
Do you plan implement such feature? It is really need for big content site.
Thanks

**Comment by Will-Bill** [comment]
Can you explain further what you mean? Do you mean multi-page articles?

**Comment by wwl2013** [comment]
Multi-page aricles is great, but I told about many-to-many relations between article and article list. Just like between page and tag.

**Comment by Will-Bill** [comment]
Sorry, I understand now. We have done this in custom apps of ours. Essentially every article will have 1 main section, but can also be listed in other sections. We may open source this code in the future, but at the moment we are not in a position to.
