### ISSUE TITLE
Menu navigation

### ISSUE THREAD

**Issue by jeffreyjmark** [MrCMS/MrCMS#3]
thought
"We do have a better navigation app we have built which we may release which does multi layered navigation menus as well as mobile navigation. If you are interesting I can try and share this with you." 

thought
Apr 20 at 2:38 PM
This week we will release Mr CMS 0.5. Will also make this available for you. 
Apologies for the delays.

Is the multi layered navigation include in 0.5.?  I don't see it.

**Comment by Will-Bill** [comment]
Hi Jeffrey, please see here: https://github.com/MrCMS/Mobile-Friendly-Navigation

**Comment by benjaminbigot** [comment]
Great ! Just what i'm looking for ^_^

**Comment by jeffreyjmark** [comment]
Thanks for uploading will
