### ISSUE TITLE
Consuming data from external source

### ISSUE THREAD

**Issue by tainazao** [MrCMS/MrCMS#36]
Hello there,

I'm trying to find the best way to consume external data, it could be with C#/Json or Jquery/Json. I would create an App for it, my question is: Does MrCMS has in his built any libary or something related to help me in this decision?

**Comment by gmstr** [comment]
We haven't got anything specific built in, but for the C# part if you know what JSON you're going to be consuming, something like this would probably work well: http://json2csharp.com

As for client side, am I missing something or are you talking about consuming JSON with JavaScript? Because that should just happen.

**Comment by tainazao** [comment]
There is an Web Api and when its url is executed it gives me back the Json data, I think this can be done with Jquery, but for client side yes this for sure will be consumed with javascript as you mentioned. Given the scenario what would be the best way to achieve this in MrCms: with http://json2csharp.com or anything else?

**Comment by gmstr** [comment]
Ah, sorry, I'm with you now, there's still nothing built in, but it's something that we've had to deal with in implementations before. I'd use the site to generate your POCOs for consumption, and then this is a non-bespoke version of the class I've used to do my consumption with:
```
using System.Net;
using MrCMS.Web.Apps.CustomApp.Calls;
using MrCMS.Web.Apps.CustomApp.Settings;
using Newtonsoft.Json;

namespace MrCMS.Web.Apps.CustomApp.Services
{
    public class SimpleExecuteApiGet
    {
        private readonly APISettings _apiSettings;

        public SimpleExecuteApiGet(APISettings apiSettings)
        {
            _apiSettings = apiSettings;
        }

        public T Execute<T>(APICall<T> apiCall)
        {
            var payload = GetPayload(apiCall);
            return JsonConvert.DeserializeObject<T>(payload);
        }

        public string GetPayload<T>(APICall<T> apiCall)
        {
            using (var webClient = new WebClient())
            {
                return webClient.DownloadString($"{_apiSettings.APIUrl.TrimEnd('/')}/{apiCall.Url}");
            }
        }
    }
}
```
which you'd create an interface from, and use the same way as any other service.
Also APICall<T> is the following:
```
    public abstract class APICall<T>
    {
        public abstract string Url { get; }
    }
```
where you're basically using a Command pattern, and building up the required URL from the instantiation of your concrete APICall, allowing you to pass in ids/query parameters etc, so you'd have a call like this;
```
    public class GetJobInfo : APICall<JobInfo>
    {
        private readonly int _id;

        public GetJobInfo(int id)
        {
            _id = id;
        }

        public override string Url => $"jobs/{_id}";
    }
```
and call it like this:
```
        public JobInfo GetInfo(int id)
        {
            return _executeApiGet.Execute(new GetJobInfo(id));
        }
```

I'm sure there's a library for doing this stuff kicking about somewhere, but that's been my approach, for what it's worth, as I've needed to use custom WebClients and implement caching, so this allowed me to add those in the relevant places.

Hope it's enough to get you going.

**Comment by tainazao** [comment]
I Appreciate you help so much, here is my Json object:

```
{
  "Anuncios": [
    {
      "AnuncioId": 100,
      "MarcaNome": "VW",
      "ModeloNome": "Jetta",
      "VersaoNome": "2.0 ConfortLine",
      "DataInclusao": "2016-11-25T12:05:20",
      "AnuncianteNome": "Empresa Xpto"
    },
    {
      "AnuncioId": 105,
      "MarcaNome": "Fiat",
      "ModeloNome": "Punto",
      "VersaoNome": "1.4 Fire",
      "DataInclusao": "2016-11-25T12:10:15",
      "AnuncianteNome": "Empresa Xpto"
    }
  ]
}
```

And my class:
```
public class Anuncio
{
 public long AnuncioId { get; set; }
 public string MarcaNome { get; set; }
 public string ModeloNome { get; set; }
 public string VersaoNome { get; set; }
 public DateTime DataInclusao { get; set; }
 public string AnuncianteNome { get; set; }
}
```

I'm fairly new on MrCMS and if it's not too much to ask, can you gimme a little help right here just a sample code between my class and the code you given. Once again Thank You!

**Comment by Will-Bill** [comment]
Sorry, we are not able to help with code examples beyond the above. We are extremely busy on this project and internal ones at the moment so we need to close this issue.
