### ISSUE TITLE
Confused on multiple sites within mrcms 

### ISSUE THREAD

**Issue by vtan31** [MrCMS/MrCMS#37]
So if I add multiple sites within mrcms, would i then publish the same codebase for that other site? 

Can you give a brief description of how themes work for multiple sites?  I figured out how to override the theme by keeping the same file structure as the root apps folder.  How would that work when adding a site?  It seems like there can only be a single theme for all sites within mrcms.  

Thanks

**Comment by DucThanhNguyen** [comment]
You can add multiple sites with different domains to one instance of MrCMS. i.e you have to publish MrCMS only one time to the web server, point all the other domains to the site, then add new site for each domain in MrCMS Admin (System/Sites).

You can also add multiple themes in the folder **MrCMS.Web/Themes/** beside the existing Default theme, then you can choose theme for each site in the admin navigation **System/Settings/Site Settings** -> tab **Site Settings** -> Theme.

**Comment by vtan31** [comment]
Thanks,  

I think i'm following... I think where I got confused was is that I'm running this locally right now as I'm integrating a theme and trying to write some apps and I wasn't quite sure how multiple sites would interact.

It now makes sense that I would have to test against multiple domains or setup other local webservers.

Sorry for the silly question... When you say point all the other domains to the site.  Do you mean by updating the domain dns to the hosting dns of where mrcms is at?  I guess I'll just have to try it out.

Thanks

**Comment by vtan31** [comment]
Oh sweet!!!  I understand now...  I just had to point my domain file location to wherever mrcms files are.  This is a really cool cms.  I'm liking it a lot.  Thanks

**Comment by DucThanhNguyen** [comment]
I also like this CMS and I've been using it for many website projects. But this repo is very inactive recently. Perhaps its authors has been busy.

**Comment by Will-Bill** [comment]
We're busy on a different branch at the moment, development is still underway. Glad this has been sorted.
