### ISSUE TITLE
Page Publish Date throws error on save with en-US culture

### ISSUE THREAD

**Issue by JosephMDavis** [MrCMS/MrCMS#46]
Hi,

We have run into an issue where the chosen Site Culture isn't used on the PublishOn textbox when editing a page. It is set in the \Areas\Admin\Views\Shared\EditorTemplates\DateTime.cshtml as "{0:dd/MM/yyyy HH:mm}". This causes the current PublishOn value to be, for example, "20/12/2015 17:00". This results in a validation error of "The value '20/12/2015 17:00' is not valid for Publish On" because our site is set to use the en-US culture so the validation thinks that there should be a month in the first set of digits and 20 is obviously not a month. 

The fix for this is very simple. Change the format specified in the DateTime.cshtml to be "{0:g}", which is the General Date Short Time specifier. This will cause the format to be automatically chosen based on the culture. The culture is used when the PublishOn is validated so it needs to be used on the textbox itself.

Note, if you select a time using the jquery date picker, the correct format is used for the chosen culture.

Also, when the culture is set to en-US, the page tries to load "/Areas/Admin/Content/Scripts/lib/jquery/ui/i18n/jquery.ui.datepicker-en-US.js" but this file doesn't exist, probably because en-US is the default culture of the jquery.ui.datepicker library. I'm not sure where this file is being called so the only fix I have for this issue is to create the file. Ideally, whatever is calling the file shouldn't call a culture-specific file when en-US culture is used.

Thanks,
Joe

**Comment by Will-Bill** [comment]
Thanks for reporting this, we will take a look

**Comment by gmstr** [comment]
Fixed in release v0.5.1.3
