### ISSUE TITLE
StackOverflowException was unhandled

### ISSUE THREAD

**Issue by mulur** [MrCMS/MrCMS#47]
Hi,

Error getting site replication processing..

ERROR DETAIL :
http://..../System.StackOverflowException was unhandled
Message: An unhandled exception of type 'System.StackOverflowException' occurred in TextPageProxyAssembly

**Comment by Will-Bill** [comment]
Can you post the full stack for me?

**Comment by mulur** [comment]
Hello,

We have a more important problem. The machines we deployed are collapsing in less than a week. Server CPU usage is too high. I could not find a solution. Instant 3500 request coming on the site. I think it's about tasks. Do you have any idea about the solution?

**Comment by mulur** [comment]
![mrcms](https://cloud.githubusercontent.com/assets/26762310/24796497/d67ca810-1b95-11e7-8000-2a02b48dce71.png)
----------------
![mrcms](https://cloud.githubusercontent.com/assets/26762310/24796607/48b565c0-1b96-11e7-8315-909c9b016e89.png)
----------------
![mrcms](https://cloud.githubusercontent.com/assets/26762310/24796647/7771388a-1b96-11e7-8326-b2d8e13cb713.png)
----------------
![mrcms](https://cloud.githubusercontent.com/assets/26762310/24796752/f7c3e1b8-1b96-11e7-95e0-8e4dbfc8e8b0.png)

**Comment by mulur** [comment]
Hosting Answer:

Thank you for your reply. On a VPS server, you will definitely have more resources and such issues can be avoided. But if the number of open MySQL connections continue to grow, you can face resource issues on a VPS as well. We understand you also have a web developer involved. Can you get in touch with him and ask to correct the issue related to MySQL connections being left open by your application? If he can resolve the MySQL connection issue, your website should work on our shared server as well. If that is not possible, the other option is to upgrade to a VPS product which we will be launching soon. We do not have an ETA at the moment. If you have any further questions or need additional assistance, please do let us know.

**Comment by rusvald** [comment]
Hello!
I have more info about the problem.
This appear when site replication procedure try save object in
\MrCMS\DbConfiguration\MrCMSSession.cs
`public object Save(object obj)
{
            ...
            return _session.Save(obj);
}`

with type `WebPageProxy` instead `TextPage`

this type of object retrived from original with right type TextPage in this point of code
\MrCMS\Helpers\EntityHelper.cs
`public static T ShallowCopy<T>(this T entity) where T : SystemEntity
{
            var type = entity.GetType();
			...
}`

**Comment by Will-Bill** [comment]
Are you just using the standard Mr CMS project? Where you are getting a proxy error use .UnProxy().

**Comment by rusvald** [comment]
Hello!
Thanks for response.
I have use 0.1.5.2 version of MrCMS with extended model WebPage by 2 properties and other small changes to core, with custom apps.
Your suggestion had help me to solve the trouble in this way:
\mrcms\services\clonesite\copywebpages.cs
`private IEnumerable<Webpage> GetWebpageCopies(Site @from, Site to, SiteCloneContext siteCloneContext, Webpage fromParent = null, Webpage toParent = null)
        {
           ...
            foreach (Webpage webpage in webpages)
            {
                Webpage copy = webpage.Unproxy().GetCopyForSite(to);`
Thank you very much.
