### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by poolpro2017** [MrCMS/MrCMS#48]
Hello, I have a few questions, 

1. In reference to MobileFriendlyNavigation. 
          How do i let it display more than 3 sets of sub categories. I cant seam to get more than 3 dropdowns.
2. is there a reason you are using Niject MVC 3? I have upgraded to the MVC 5 and seams to work fine.

**Comment by Will-Bill** [comment]
1 - I didn't think there was a limit, however step through the code and check where the child nodes are being selected.
2 - No, just not been updated. MVC 5 should be fine.

**Comment by poolpro2017** [comment]
I am sorry, i was speaking about the categories in ecommerce. i will look to see if i can find it.
