### ISSUE TITLE
What is the future roadmap?

### ISSUE THREAD

**Issue by poolpro2017** [MrCMS/MrCMS#49]
Hello,

Curious as to what the road-map is for the project, as maybe i can help you move forward. I was thinking of making bootstrap, and scripts global in the project with grunt and bower, This will make things easier for update of the project, and we can add a provision for grunt and bower in the apps, and have a standard to the content folder of each app, and each app can have its required files that would override any global if present. This would also open the door for future themeing. Just a suggestion. Please let me know if i can be of assistance.

**Comment by Will-Bill** [comment]
We are working on a 1.0 version or Mr CMS using .NET Core 1.1. There are several big changes with this and we are rewriting the core parts to Mr CMS. Details will be released when we are slightly further down the development road.

**Comment by MDIRashid** [comment]
Great news... I am here for any assistance. :1st_place_medal:

**Comment by poolpro2017** [comment]
Yes that is good news, And if i can be of any help please let me know. and thanks for all your hard work.
