### ISSUE TITLE
Entities Items Deletion

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#51]
Good day,
I want to show list of deleted entities items but noticed that NHibernate Queryover or Query automatically ignores any entry or item that has been marked as IsDeleted. I want to show list of both deleted and not deleted entries. I have checked the MrCmsController and MrCmsSession but couldn't located where to disabled the IsDeleted clause.
Where was the IsDeleted clause located in MrCms library.

Cheers

**Comment by Will-Bill** [comment]
Hi there, use NotDeletedFilterDisabler

using (new NotDeletedFilterDisabler(session)
{
//query
}

**Comment by carlospence** [comment]
Thanks.
