### ISSUE TITLE
Deploying on AWS (Elasticbean permission issues)

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#60]
Goodday,

Have anyone tried deploying MrCMS on AWS successfully with all folder permissions fully set?

**Comment by Will-Bill** [comment]
How did you get on with this? I've not tried but it shouldn't be an issue

**Comment by carlospence** [comment]
ELastic bean was not giving the application permission to auto-create folder and files in the app-data. I had to leave AWS and move finally to Azure. I wanted options in hosting.

**Comment by Will-Bill** [comment]
It should be fine there, but we do need write options for installation. Mostly though instal happens at the dev level so we don't worry to much about hosted environments for installs.
