### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#64]
I understood the structure of an application. Pages and widgets that each app has.
But when I work with the user interface, it's very obscure and dumb. Is there someone to explain to me?

**Comment by codeendevor** [comment]
Please be more specific. Are we talking the GUI? USERS? ROLES? ACL?  Microsoft.AspNet.Identity?. The system uses a ASP.NET Identity Custom Storage Provider from the people entity, that call IUser from Microsoft.AspNet.Identity. More information here [https://docs.microsoft.com/en-us/aspnet/identity/overview/extensibility/overview-of-custom-storage-providers-for-aspnet-identity](https://docs.microsoft.com/en-us/aspnet/identity/overview/extensibility/overview-of-custom-storage-providers-for-aspnet-identity). I was working on a new implementation of the user system for better management with menus and separation of system users to visitor users, but was told they are creating a new version using CORE.

If you need some specific information and i can help please let me know.

**Comment by Sourcenew** [comment]
Thank you for the trouble you are doing,

how i can define layout? i need two layout(ltr and rtl) for handle multi language website.
look at this website:http://www.kurdistan24.net/en/default
how i can define language page. just separate with url?

actually i need this:

-Define Layouts for each language
-Define Some language and add user for each language
-Define just author user
-Where is the category. is it a Article Lists?

**Comment by Will-Bill** [comment]
You can add as many layouts as you wish and you get use page templates to assign layouts.

Look at the ecommerce project for a more in depth example. 

I wouldn't have thought you need multiple layouts per language. If it just a case of changing CSS for rtl/ltr ref then change that in your base layout. E.G is site id is x then include y.

**Comment by Sourcenew** [comment]
I wrote helper class for manage multilanguage css and js..  rtl or ltr version or per languange.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
