### ISSUE TITLE
Remove unauthorized characters

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#65]
<div id="carousel-@Model.Name" class="carousel slide" data-ride="carousel">

in core app you use Model.Name as Id but before it you have to remove Unauthorized characters like space or ...

or i suggest you use "widget name+ guid". it's very better idea

**Comment by Sourcenew** [comment]
i solved it in my widget:
https://www.dropbox.com/s/colvmdmqkxpgmjk/2.png?dl=0

**Comment by Sourcenew** [comment]
id="carousel-@(WidgetKeyGenerator.New(lastKey:false))"

**Comment by Will-Bill** [comment]
probably just use the guid is best. will get this added.

**Comment by Sourcenew** [comment]
yeah but this is actually guid but have some more params... like last key(for some use)... or save Id per widget for future use or ...
next week i will push some add figure to mrcms
