### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#66]
i wrote some widget for article app like slider and ...
how i can add in the GitHub?

**Comment by Sourcenew** [comment]
https://www.dropbox.com/s/kwqvtu4jfup5jfu/i1024%5Ecimgpsh_orig.png?dl=0

**Comment by Sourcenew** [comment]
https://www.dropbox.com/s/colvmdmqkxpgmjk/2.png?dl=0

**Comment by codeendevor** [comment]
Dalir,

Not really sure what you are trying to do at this point, You are jumping around allot. As for themes and lang, If i am correct you would create your themes and language for each theme on different sites, MrCMS has the ability to add sites under sites. as for your code you shown, what are you trying to accomplish? Have you looked at the Ecommerce project to get more ideas of how you override the core project?

**Comment by Sourcenew** [comment]
Sorry for many message, I'm just happy

I'm in learning mrcms, now i understood mrcms, and for my test I'm trying to design this website:
http://www.kurdistan24.net/en/default

**Comment by Sourcenew** [comment]
This Saturday i will look at E-commerce app.
Thank you for all your jobs

**Comment by Sourcenew** [comment]
https://www.dropbox.com/s/y4diq1uq2gzqesr/ArticleSlider.png?dl=0

my first widget

**Comment by Will-Bill** [comment]
If you would like to contribute please feel free to do a pull request.

Congrats on first widget!
