### ISSUE TITLE
Multilingual Pages

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#68]
Hi dear, Finally, the design of a news website is over. But I have a problem with multilingualism. How to separate the pages of each language(for example each language have own pages and own navbar)?
And that every author should have access to their language news.

**Comment by Sourcenew** [comment]
:-\

**Comment by Sourcenew** [comment]
When I defined a site. How do I create a page for that site? In the list of pages, it does not ask which site

**Comment by Will-Bill** [comment]
Use multisite for multiple sites. See other thread RE sites.
