### ISSUE TITLE
Add Site

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#69]
When I defined a site. How do I create a page for that site? In the list of pages, it does not ask which site

**Comment by Will-Bill** [comment]
In the top right hand corner there is a site selector. Use this to jump between sites.

If you are in development, use the app setting debugSiteId

**Comment by Sourcenew** [comment]
i have to install another version in that destination site. 
and in the database you separate data by siteId
i got it. thank you
