### ISSUE TITLE
ThirdPartyAuth

### ISSUE THREAD

**Issue by YoChen** [MrCMS/MrCMS#7]
API Callback address，How to write it?

is "http://Domain.com/login" ?

or "http://Domain.com/ExternalLogin" ?

**Comment by YoChen** [comment]
"400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request: http://Domain.com/signin-google did not match a registered redirect URI."

When I User Google auth login.

**Comment by Will-Bill** [comment]
Check in the google api console you are not linking to httpS.
