### ISSUE TITLE
How to using MrCMS ?

### ISSUE THREAD

**Issue by nqbjnh** [MrCMS/MrCMS#71]
I find on mrcms.com website about document, but it nothing.
Plz, share for me. How to using MrCMS ?
Thank you.

**Comment by nqbjnh** [comment]
If i have any problem i will contact for you.
Thank you so much.

**Comment by Will-Bill** [comment]
Sorry we are a really small team so documentation is not great. If you have specific questions please ask, or look at the Ecommerce project for a larger example of an implementation.

**Comment by hansonho** [comment]
> I was like you a month ago...
> and ask vey question but there is no support...
> after that I tried to solve my problems by create my app in mrcms cms-framework.
> now my small website is ready:
> [www.hengaw.net](http://www.hengaw.net)
> 
> multilingual (4 language) and ...
> if I can help you for just put your email here... I can describe something's useful for you :)
