### ISSUE TITLE
Support Bootstrap 4

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#72]
i think it's better use template for support bootstrap versions than embed code...
it was very hard to change pagging system to bootstrap 4. but if you use template html or somthing else  it will be good

**Comment by codeendevor** [comment]
I run bootstrap 4 with jQuery 3.3.1 and updated all packages except for NHibernate, and i use all packages from NuGet now so easy to update to newest version.

**Comment by codeendevor** [comment]
I have also created a bunch of bootstrap widgets that make it easy to add things to pages. and also created content widgets to help break the page up more allowing for widgets between content. Now you know you could create an app just for your theme, this will inject bootstrap 4 for you using IStylesheetBundle.

**Comment by codeendevor** [comment]
@Will-Bill glad to see you back in action, what branch would you like future pull requests to.

**Comment by Will-Bill** [comment]
I have switch the project to show develop branch by default now, so that is the one which pull requests will come to which is correct.

**Comment by Sourcenew** [comment]
i done it with bootstrap 4.
but i say paging system (Article list) was hard to convert. because it not use html template. you just create html tags dynamically...
but if you use html template and just replace it. it was faster and easy to change template
