### ISSUE TITLE
admin dashboard template

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#74]
hi,
i want to change admin dashboard template to this:
https://github.com/puikinsh/Adminator-admin-dashboard

-Bootstrap4
-Free
-Good design

**Comment by Will-Bill** [comment]
Do it! 👍

**Comment by Sourcenew** [comment]
can i have your email address?
not for asking question. just for showing you somthing(new design)
this is my mail: dalir.bajlany2000@live.com

**Comment by Will-Bill** [comment]
will at mrcms.com
