### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#75]
Documents exporting has failed. Please try again and contact system administration if error continues to appear.

for large count of document ...

about 15000

**Comment by Will-Bill** [comment]
Either increase resource availability (CPU/RAM) or do some work to optimise this.

I am marking as an enhancement and will look to optimise in future.

**Comment by Sourcenew** [comment]
i write my own export and import application. its work directly to database. i move 33000 article from wordpress to mrcms without any problem.
adding UrlHistory,a Document Version,and tags...

**Comment by Sourcenew** [comment]
ok. but i'm thinking now. you have to insert destination articleList id manually, i have to create a dropdown box for it and some documents. i will send it to you this week. i'm very happy dear to do this. it's my first git-hub :)

**Comment by Sourcenew** [comment]
sorry for delay. i'm just dropped in two big project last year :|

i will add it in mrcms (import from wordpress) soon (maybe before april)
