### ISSUE TITLE
Custom domain hosting on Azure

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#81]
I hosted on Azure and wanted to use custom domain. After doing all the necessary dns settings. The domain is always redirecting to [appname].azurewebsites.net instead of loading the azure webapp on the domain. Do I have to create a site bearing the domain name I created.

**Comment by Will-Bill** [comment]
Make sure you clear cache - you can do this by restarting the website.

**Comment by carlospence** [comment]
I have clear the cache and restarted the server on Azure and still the same thing

The hosting on Azure is http://bukamserver.azurewebsites.net/

While am trying am using a custom domain http://syncbus.bukam.xyz.

Instead of showing the custom domain name, it is always redirecting.

I have another react web app on Azure  http://bukamapp.azurewebsites.net

I used a custom domain http://client.bukam.xyz and it is working as it should. What do you think is d CMS Multsite setup issue 

![download 21](https://user-images.githubusercontent.com/12647064/43576880-4a0b2f04-9642-11e8-954d-1ee5f6638b95.png)


--

**Comment by Will-Bill** [comment]
You need to update the URL from bukamserver.azurewebsites.net to your new
URL.

**Comment by Will-Bill** [comment]
Staging URL is if you use a slot in azure you can assign that here. So you
don't get the redirect behavior whilst warming up / testing the slot site
on a different url e.g mysite-staging.azurewebsite.net.

**Comment by carlospence** [comment]
Thanks worked perfectly well, but still want to know Staging Url meant and how Redirected Domains works
