### ISSUE TITLE
Directing multiple urls to the same site 

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#82]
Is it possible to make multiple urls get the information of a particular site instead of them having their data differently.

e.g I have site http://localhost:9090, http://localhost:8090, http://localhost:7090, I want the three sites to pick the data of http://localhost:9090 instead of them having their separate data.

**Comment by Will-Bill** [comment]
Not possible as it stands. Should be a simple code change to make happen though.

Why are you not using the multi-site functionality? Loading the same site on multiple URLs will be bad for SEO

**Comment by Will-Bill** [comment]
Use multi-site if you want to have multiple domains which share the same functionality but have different content. E.G if you are an events company which runs 10 events each year, each will have different domain and content but the functionality of the event app will be the same for all sites.

If you want for whatever reason two have multiple domains on a single site you would have to update the logic of BaseUrl in the Site Entity. A simple suggestion would be to allow comma-separated list here. E.G www.domain1.com, www.domain2.com etc.

Then update the logic which does the redirection in MrCMSRequiresSiteRedirectRouteHandler. You'd need to split on comma and then check. 

There will be other code to update too, e.g CurrentSite in CurrentRequestData.

**Comment by carlospence** [comment]
Ok thanks a bunch
