### ISSUE TITLE
IDocumentService Deprecated 

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#83]
I am wondering why IDocumentService was deprecated from version 0.6, was trying to migrate my app to the latest version and used IDocumentService in my Setup Installation. I guess it was deprecated in favor of IGetDocumentByUrl. Moreso, the Ecomerce app have not been updated to the latest version of MrCMS.

**Comment by Will-Bill** [comment]
The develop branch of Mr CMS is latest, but not released. For release there is a branch v0.6 which has hotfixes in. For projects always use master branch until release is made.
