### ISSUE TITLE
Config SSL. 

### ISSUE THREAD

**Issue by ntkien8994** [MrCMS/MrCMS#87]
i can't config SSL. 
Example:
 mydomain :  http://www.mrcms.me.local
when i try to access https://www.mrcms.me.local it redirect to http://www.mrcms.me.local

Please tell me that problem and how to config SSL
Thanks!

**Comment by codeendevor** [comment]
After configuring SSL in IIS properly go to Admin, Under Settings>Site Settings click the tab for Site Settings and Check the check box for use SSL in Admin and Use the SSL Everywhere.

**Comment by ntkien8994** [comment]
i did it but not working. after configuring it always redirects to http://www

**Comment by codeendevor** [comment]
1. is this a public site?
2. What SSL provider are you using.
3. Did you place the proper Settings in IIS for the domain.
4. Have you tried to go directly to https://yourdomain.me

I am not understanding the local, part as not sure how you are securing a local site.

**Comment by Sourcenew** [comment]
after config your domain and setup you ssl, then try to active ssl it in mrcms setting, you have problem with your domain name spaces

**Comment by Will-Bill** [comment]
It looks like its a localhost - we don't do SSL redirection for localhosts.
