### ISSUE TITLE
How can we manage multiple languages in MrCMS ?

### ISSUE THREAD

**Issue by OlivierAlbertini** [MrCMS/MrCMS#9]
Hi,

Good project !
I'm running your project and it seems that the project doesn't manage different languages, right ?

**Comment by Will-Bill** [comment]
We have localisation (See system->Resources) at the site level at the moment. If you wanted to run multiple languages you would need to set up multiple sites. E.G

en.yourdomain.com
fr.yourdomain.com

After you duplicate a site you would go into settings and set the culture. You would then override the resources and set up the page content to be language specific.

We do have a plan to implement multi-lingual capabilities on a per site basis but its not on the immediate roadmap. If you'd like to contribute to the project then of course feel free :+1:

**Comment by hyrmedia** [comment]
I might be interested in contributing to this. Can you elaborate on what's been discussed thus far? Or could we have a conversation about it at some point?

**Comment by Will-Bill** [comment]
We've had an initial discussion this end how we might go about implementing multilingual capabilities into Mr CMS, but nothing concrete or properly specified yet. 

Be more than happy you contributing, and more than willing discuss this with you if you like?

**Comment by yannickberthoud** [comment]
I can participate for french translation ! contact me without problems :)

**Comment by okarpov** [comment]
@OlivierAlbertini Hello, any updates on it?
Are you planning to implement more "friendly and seo optimized" way for multi-language?
like:
- domain.com - for english
- domain.com/en - for english
- domain.com/de - for german
etc.
?
