### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by rsoftware00** [MrCMS/MrCMS#92]
Hi All,
i'm trying to manage SEO information in the CMS. After insert the words in the "SEO Target Phrase" section (in the page), i press "Analyze" button and then "Save".
after this, i press "view" to show the page in the browser and "view source" (right click).  Now, if I try to search for the previously entered words I can't find them.
it's normal? where do I find the SEO words inserted in mscms?

**Comment by Will-Bill** [comment]
The target phrase is what you would like to be found for in SEs.

The analyse button does basic analysis of your page content against a set of rules and shows you the results of what actions may need to be taken based of the target phrase.

I am not sure what you mean by "Now, if I try to search for the previously entered words I can't find them."
