### ISSUE TITLE
"DNC" Populate Pages with Published = true

### ISSUE THREAD

**Issue by kschost100** [MrCMS/MrCMS#96]
On install of Dotnet Core feature, after install i get a blank screen, after looking through sone of the issues i found that the pages are not published, i have tried the following with no success.

SetupCoreWebpages.cs
`
_session.Transact(session =>
            {

                GetAccountPages().ForEach(webpage => session.Save(webpage));

                session.Save(GetSearchPage());

                var webpages = _session.QueryOver<Webpage>().List();
                var publishOn = DateTime.UtcNow;
                webpages.ForEach(webpage =>
                {
                    webpage.PublishOn = publishOn;
                    webpage.Published = true;
                    session.Update(webpage);
                });
            });
`

But this did not work.

I have also tried adding:
`Published = true`
to each page, and still the same.

Any suggestions?

**Comment by Will-Bill** [comment]
Not seen this problem before - the set up creates the pages in a published state.

Maybe try from scratch with a new installation? Check you have the latest files from feature/dotnetcore.

The app crashing at the end is an unfortunate side effect of being cross platform - in the old Mr CMS the app crashed but IIS just auto restarts. With DNC this is not the case, you need to manually re-run the app.

Of course we want to see if we can find a work around on this, but we wanted Mr CMS to run on Linux/Mac/Windows as a priority over that installation issue.

**Comment by codeendevor** [comment]
Could it possibly be that I am using MsSQL 2017?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by codeendevor** [comment]
KscHost100 try using 2012, that did it for me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kschost100** [comment]
I will try what everyone suggests, I am using MsSQL 2016 and did try on 2 different Dev machines.

**Comment by kschost100** [comment]
> app crashing at the end

Will-Bill, where would I find the code that sets the pages as published.

**Comment by kschost100** [comment]
I may have found an issue for Published on install, Please note I'm not a great programmer I know just enough to get myself in trouble. LOL 

I have tried what codeendevor had said but did not work for me.
Anyway, Becuase I am here in the US the UTC time is different causing UTC time to be ahead by 5 hours.

The code on setup Core Webpages: `var publishOn = DateTime.UtcNow;`

`_session.Transact(session =>
            {

                GetAccountPages().ForEach(webpage => session.Save(webpage));

                session.Save(GetSearchPage());

                var webpages = _session.QueryOver<Webpage>().List();
                var publishOn = DateTime.UtcNow;
                webpages.ForEach(webpage =>
                {
                    webpage.PublishOn = publishOn;
                    session.Update(webpage);
                });
            });`

Uses UK DateTime and in MrCMS.Events.Documents.MarkWebpageAsPublished it uses `var now = _getDateTimeNow.LocalNow;`

`public void Execute(OnUpdatingArgs<Webpage> args)
        {
            var now = _getDateTimeNow.LocalNow;
            var webpage = args.Item;
            if (webpage.PublishOn.HasValue && webpage.PublishOn <= now && webpage.Published == false)
            {
                webpage.Published = true;
            }
        }`

`var now = _getDateTimeNow.LocalNow;` **is 5 hours behind** `var publishOn = DateTime.UtcNow;` Causing `webpage.PublishOn <= now` to be False.

I have changed ` var publishOn = DateTime.UtcNow;` to ` var publishOn = DateTime.Now;` and this seams to work.

I do not want to break anything and would like your thoughts on the matter.

Thanks in advance

**Comment by Will-Bill** [comment]
Thanks for bringing this to our attention, we will fix.

**Comment by kschost100** [comment]
Thank You, and Thanks for all your hard work. Wish I could help but as I said, Takes me a long time to figure things out. I am mostly a front end guy.

**Comment by Will-Bill** [comment]
Here is the fix: https://github.com/MrCMS/MrCMS/commit/2ae242e681fb7c0ae4beff794902af9040fd7cae
