### ISSUE TITLE
"DNC" Can themes be built like apps?

### ISSUE THREAD

**Issue by kschost100** [MrCMS/MrCMS#97]
Can we build themes like we do apps, or is it just for Views and Static files?

**Comment by Will-Bill** [comment]
Themes are now project based so they can be portable or potentially shared through a store.

They are not meant to have app-functionality in them, simply serve the purpose of theming the apps you have in your project.

Apps and Themes are registered in Startup.cs:

`context.RegisterApp<MrCMSArticlesApp>();
                context.RegisterTheme<RedTheme>();`

**Comment by kschost100** [comment]
As i expected. Thank you
